/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTrackResponseDto
 */
export interface AddTrackResponseDto {
    /**
     * 
     * @type {boolean}
     * @memberof AddTrackResponseDto
     */
    newTrackAdded?: boolean;
}

/**
 * Check if a given object implements the AddTrackResponseDto interface.
 */
export function instanceOfAddTrackResponseDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddTrackResponseDtoFromJSON(json: any): AddTrackResponseDto {
    return AddTrackResponseDtoFromJSONTyped(json, false);
}

export function AddTrackResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTrackResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newTrackAdded': !exists(json, 'newTrackAdded') ? undefined : json['newTrackAdded'],
    };
}

export function AddTrackResponseDtoToJSON(value?: AddTrackResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'newTrackAdded': value.newTrackAdded,
    };
}

