/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationMethod
 */
export interface AuthenticationMethod {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationMethod
     */
    value?: string;
}

/**
 * Check if a given object implements the AuthenticationMethod interface.
 */
export function instanceOfAuthenticationMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthenticationMethodFromJSON(json: any): AuthenticationMethod {
    return AuthenticationMethodFromJSONTyped(json, false);
}

export function AuthenticationMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function AuthenticationMethodToJSON(value?: AuthenticationMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

