/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Href
 */
export interface Href {
    /**
     * 
     * @type {string}
     * @memberof Href
     */
    href?: string;
}

/**
 * Check if a given object implements the Href interface.
 */
export function instanceOfHref(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HrefFromJSON(json: any): Href {
    return HrefFromJSONTyped(json, false);
}

export function HrefFromJSONTyped(json: any, ignoreDiscriminator: boolean): Href {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
    };
}

export function HrefToJSON(value?: Href | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
    };
}

