/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuth2RefreshToken
 */
export interface OAuth2RefreshToken {
    /**
     * 
     * @type {string}
     * @memberof OAuth2RefreshToken
     */
    tokenValue?: string;
    /**
     * 
     * @type {Date}
     * @memberof OAuth2RefreshToken
     */
    issuedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OAuth2RefreshToken
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the OAuth2RefreshToken interface.
 */
export function instanceOfOAuth2RefreshToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OAuth2RefreshTokenFromJSON(json: any): OAuth2RefreshToken {
    return OAuth2RefreshTokenFromJSONTyped(json, false);
}

export function OAuth2RefreshTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2RefreshToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenValue': !exists(json, 'tokenValue') ? undefined : json['tokenValue'],
        'issuedAt': !exists(json, 'issuedAt') ? undefined : (new Date(json['issuedAt'])),
        'expiresAt': !exists(json, 'expiresAt') ? undefined : (new Date(json['expiresAt'])),
    };
}

export function OAuth2RefreshTokenToJSON(value?: OAuth2RefreshToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tokenValue': value.tokenValue,
        'issuedAt': value.issuedAt === undefined ? undefined : (value.issuedAt.toISOString()),
        'expiresAt': value.expiresAt === undefined ? undefined : (value.expiresAt.toISOString()),
    };
}

