/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClientRegistration } from './ClientRegistration';
import {
    ClientRegistrationFromJSON,
    ClientRegistrationFromJSONTyped,
    ClientRegistrationToJSON,
} from './ClientRegistration';
import type { OAuth2AccessToken } from './OAuth2AccessToken';
import {
    OAuth2AccessTokenFromJSON,
    OAuth2AccessTokenFromJSONTyped,
    OAuth2AccessTokenToJSON,
} from './OAuth2AccessToken';
import type { OAuth2RefreshToken } from './OAuth2RefreshToken';
import {
    OAuth2RefreshTokenFromJSON,
    OAuth2RefreshTokenFromJSONTyped,
    OAuth2RefreshTokenToJSON,
} from './OAuth2RefreshToken';

/**
 * 
 * @export
 * @interface OAuth2AuthorizedClient
 */
export interface OAuth2AuthorizedClient {
    /**
     * 
     * @type {ClientRegistration}
     * @memberof OAuth2AuthorizedClient
     */
    clientRegistration?: ClientRegistration;
    /**
     * 
     * @type {string}
     * @memberof OAuth2AuthorizedClient
     */
    principalName?: string;
    /**
     * 
     * @type {OAuth2AccessToken}
     * @memberof OAuth2AuthorizedClient
     */
    accessToken?: OAuth2AccessToken;
    /**
     * 
     * @type {OAuth2RefreshToken}
     * @memberof OAuth2AuthorizedClient
     */
    refreshToken?: OAuth2RefreshToken;
}

/**
 * Check if a given object implements the OAuth2AuthorizedClient interface.
 */
export function instanceOfOAuth2AuthorizedClient(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OAuth2AuthorizedClientFromJSON(json: any): OAuth2AuthorizedClient {
    return OAuth2AuthorizedClientFromJSONTyped(json, false);
}

export function OAuth2AuthorizedClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2AuthorizedClient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientRegistration': !exists(json, 'clientRegistration') ? undefined : ClientRegistrationFromJSON(json['clientRegistration']),
        'principalName': !exists(json, 'principalName') ? undefined : json['principalName'],
        'accessToken': !exists(json, 'accessToken') ? undefined : OAuth2AccessTokenFromJSON(json['accessToken']),
        'refreshToken': !exists(json, 'refreshToken') ? undefined : OAuth2RefreshTokenFromJSON(json['refreshToken']),
    };
}

export function OAuth2AuthorizedClientToJSON(value?: OAuth2AuthorizedClient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientRegistration': ClientRegistrationToJSON(value.clientRegistration),
        'principalName': value.principalName,
        'accessToken': OAuth2AccessTokenToJSON(value.accessToken),
        'refreshToken': OAuth2RefreshTokenToJSON(value.refreshToken),
    };
}

