/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartyCreatedDto
 */
export interface PartyCreatedDto {
    /**
     * 
     * @type {string}
     * @memberof PartyCreatedDto
     */
    joinCode?: string;
}

/**
 * Check if a given object implements the PartyCreatedDto interface.
 */
export function instanceOfPartyCreatedDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PartyCreatedDtoFromJSON(json: any): PartyCreatedDto {
    return PartyCreatedDtoFromJSONTyped(json, false);
}

export function PartyCreatedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartyCreatedDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'joinCode': !exists(json, 'joinCode') ? undefined : json['joinCode'],
    };
}

export function PartyCreatedDtoToJSON(value?: PartyCreatedDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'joinCode': value.joinCode,
    };
}

