/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthenticationMethod } from './AuthenticationMethod';
import {
    AuthenticationMethodFromJSON,
    AuthenticationMethodFromJSONTyped,
    AuthenticationMethodToJSON,
} from './AuthenticationMethod';

/**
 * 
 * @export
 * @interface UserInfoEndpoint
 */
export interface UserInfoEndpoint {
    /**
     * 
     * @type {string}
     * @memberof UserInfoEndpoint
     */
    uri?: string;
    /**
     * 
     * @type {AuthenticationMethod}
     * @memberof UserInfoEndpoint
     */
    authenticationMethod?: AuthenticationMethod;
    /**
     * 
     * @type {string}
     * @memberof UserInfoEndpoint
     */
    userNameAttributeName?: string;
}

/**
 * Check if a given object implements the UserInfoEndpoint interface.
 */
export function instanceOfUserInfoEndpoint(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserInfoEndpointFromJSON(json: any): UserInfoEndpoint {
    return UserInfoEndpointFromJSONTyped(json, false);
}

export function UserInfoEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoEndpoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
        'authenticationMethod': !exists(json, 'authenticationMethod') ? undefined : AuthenticationMethodFromJSON(json['authenticationMethod']),
        'userNameAttributeName': !exists(json, 'userNameAttributeName') ? undefined : json['userNameAttributeName'],
    };
}

export function UserInfoEndpointToJSON(value?: UserInfoEndpoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uri': value.uri,
        'authenticationMethod': AuthenticationMethodToJSON(value.authenticationMethod),
        'userNameAttributeName': value.userNameAttributeName,
    };
}

