/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/party": {
    post: operations["create"];
  };
  "/api/v1/user/secrets": {
    get: operations["secrets"];
  };
  "/api/v1/user/me": {
    get: operations["me"];
  };
  "/api/v1/ping": {
    get: operations["ping"];
  };
}

export interface components {
  schemas: {
    AuthenticationMethod: {
      value?: string;
    };
    AuthorizationGrantType: {
      value?: string;
    };
    ClientAuthenticationMethod: {
      value?: string;
    };
    ClientRegistration: {
      registrationId?: string;
      clientId?: string;
      clientSecret?: string;
      clientAuthenticationMethod?: components["schemas"]["ClientAuthenticationMethod"];
      authorizationGrantType?: components["schemas"]["AuthorizationGrantType"];
      redirectUri?: string;
      scopes?: string[];
      providerDetails?: components["schemas"]["ProviderDetails"];
      clientName?: string;
      /** @deprecated */
      redirectUriTemplate?: string;
    };
    OAuth2AccessToken: {
      tokenValue?: string;
      /** Format: date-time */
      issuedAt?: string;
      /** Format: date-time */
      expiresAt?: string;
      tokenType?: components["schemas"]["TokenType"];
      scopes?: string[];
    };
    OAuth2AuthorizedClient: {
      clientRegistration?: components["schemas"]["ClientRegistration"];
      principalName?: string;
      accessToken?: components["schemas"]["OAuth2AccessToken"];
      refreshToken?: components["schemas"]["OAuth2RefreshToken"];
    };
    OAuth2RefreshToken: {
      tokenValue?: string;
      /** Format: date-time */
      issuedAt?: string;
      /** Format: date-time */
      expiresAt?: string;
    };
    ProviderDetails: {
      authorizationUri?: string;
      tokenUri?: string;
      userInfoEndpoint?: components["schemas"]["UserInfoEndpoint"];
      jwkSetUri?: string;
      issuerUri?: string;
      configurationMetadata?: { [key: string]: { [key: string]: unknown } };
    };
    TokenType: {
      value?: string;
    };
    UserInfoEndpoint: {
      uri?: string;
      authenticationMethod?: components["schemas"]["AuthenticationMethod"];
      userNameAttributeName?: string;
    };
    PartyCreatedDto: {
      joinCode?: string;
    };
  };
}

export interface operations {
  create: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PartyCreatedDto"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OAuth2AuthorizedClient"];
      };
    };
  };
  secrets: {
    parameters: {
      query: {
        authorizedClient: components["schemas"]["OAuth2AuthorizedClient"];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  me: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  ping: {
    responses: {
      /** Server is available - the server responds with "pong". */
      200: {
        content: {
          "*/*": string;
        };
      };
    };
  };
}

export interface external {}
