/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PlaylistDto,
} from '../models';
import {
    PlaylistDtoFromJSON,
    PlaylistDtoToJSON,
} from '../models';

export interface GetPlaylistsRequest {
    partyId: string;
}

/**
 * 
 */
export class PlaylistControllerApi extends runtime.BaseAPI {

    /**
     * Get first four playlists of the host
     */
    async getPlaylistsRaw(requestParameters: GetPlaylistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlaylistDto>>> {
        if (requestParameters.partyId === null || requestParameters.partyId === undefined) {
            throw new runtime.RequiredError('partyId','Required parameter requestParameters.partyId was null or undefined when calling getPlaylists.');
        }

        const queryParameters: any = {};

        if (requestParameters.partyId !== undefined) {
            queryParameters['partyId'] = requestParameters.partyId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/playlists`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlaylistDtoFromJSON));
    }

    /**
     * Get first four playlists of the host
     */
    async getPlaylists(requestParameters: GetPlaylistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlaylistDto>> {
        const response = await this.getPlaylistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
