# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'svq-hipqueue' }}
  REACT_APP_IS_DEBUG: ${{ false }}
  REACT_APP_BACKEND_BASE_URL: ${{ 'https://svq-backend.herokuapp.com' }}
  REACT_APP_APPLICATION_BASE_URL: ${{ 'https://svq-hipqueue.herokuapp.com' }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: CI='' npm run build --if-present

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    needs: build
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME --build-arg REACT_APP_BACKEND_BASE_URL=$REACT_APP_BACKEND_BASE_URL
        heroku container:release web -a $APP_NAME
